# Generated by Django 3.0.6 on 2021-07-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_onlineclassroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='subject_final_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject_midterm_marks',
            field=models.FloatField(default=0),
        ),
    ]
