# Generated by Django 3.0.6 on 2021-07-14 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_assignmentreportstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizReportStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_date', models.CharField(max_length=255)),
                ('assignment_message', models.TextField()),
                ('assignment_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.Staffs')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.Subjects')),
            ],
        ),
    ]
