# Generated by Django 3.0.6 on 2021-07-14 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_auto_20210713_2139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizReportStafff',
            new_name='QuizReportStaff',
        ),
    ]
